apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-library-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ai-library-operator
  template:
    metadata:
      labels:
        name: ai-library-operator
    spec:
      serviceAccountName: ai-library-operator
      containers:
        - name: ai-library-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - ai-library-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ai-library-operator"
